### ISSUE TITLE
How to add it

### ISSUE THREAD

**Issue by mopoIo** [BranchofLight/CyTube-Room-Script#9]
I really like what this script does, but I'm not sure on how to add it?

**Comment by BranchofLight** [comment]
Thanks for your interest! I previously had a how-to but have since forgot to re-add one. My bad.

To add:

1. Go to your cytube room.
2. Channel Settings -> Admin Settings
3. External Javascript
4. Use the latest build (eg. https://branchoflight.github.io/CyTube-Room-Script/dist/main.js)

Note: this will use my personal config for username colour coding. I have no intention to add modifying it as a feature right now, but you can do it yourself by either modifying the config in src/constants.js and building a new dist or modifying the dist/main.js file manually. In any case, you will then need to host it somewhere like https://www.jsdelivr.com/rawgit to be able to use the file on your cytube room. 

I'm going to close this for now, but let me know if you have any additional questions.

**Comment by mopoIo** [comment]
It worked thank you!

I don't know if you have comissions open but I'm trying to add some other features. If you do, I was wondering where I could contact you? Obviously I'm willing to pay!. Cheers.

**Comment by BranchofLight** [comment]
Sorry, I am not looking for commission work at this time.

**Comment by mopoIo** [comment]
I understand. Thank you anyways for the amazing script!
